[profile.default]
src = 'src'
out = 'out'
test= 'test'
script = 'script'
libs = ['lib']
solc_version = "0.8.19"
auto_detect_solc = false
optimizer = true
optimizer_runs = 833
bytecode_hash = "none"
cbor_metadata = false
gas_reports = ["*"]

[etherscan]
goerli = { key ="${API_KEY_ETHERSCAN}"}
sepolia =  { key ="${API_KEY_ETHERSCAN}"}
mainnet = { key ="${API_KEY_ETHERSCAN}"}

[rpc_endpoints]
  goerli = "https://goerli.infura.io/v3/${API_KEY_INFURA}"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_INFURA}"
  sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"



# See more config options https://github.com/foundry-rs/foundry/tree/master/config